spring:
  application:
    name:
      springsecurity6master
  data:
    redis:
      host: localhost
      port: 6379
#  security:
#    user:
#      name: user
#      password: 1111
#      roles: USER

server:
  port: 8098